Only decode messages at the end
We were decoding messages by chunk that could result in

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3
in position 4095: unexpected end of data

Hopefully this fixes it. It happens very seldomly so it's hard
to debug.